name: Cypress Tests

on:
  push:
    branches:
      - main  # ajuste conforme sua branch principal
  pull_request:
    branches:
      - main  # ajuste conforme sua branch principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Cypress globally
        run: npm install -g cypress

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          CI: true
